const START_KEY='atom-bcc-started-at';
const STAGES_KEY='atom-bcc-stage-statuses-v02';
const TEAMS_KEY='atom-bcc-team-owners-v02';
const MODULES_KEY='atom-bcc-module-statuses-v02';
const BLOCKERS_KEY='atom-bcc-blockers-v02';
const DOD_KEY='atom-bcc-dod-v02';
const app=document.getElementById('app');
let currentView='overview';
let timerHandle=null;

const STAGE_STATUSES=['Не начато','Подготовка','В работе','Ожидание','На согласовании','Блокер','Завершено'];
const MODULE_STATUSES=['Не начато','Проектирование','Разработка','Тестирование','Пилот','Готово','Блокер'];
const BLOCKER_STATUSES=['Открыт','В работе','Ожидаем ответ','На эскалации','Решен','Закрыт'];
const SEVERITY=['Низкая','Средняя','Высокая','Критическая'];
const PROGRESS={'Не начато':0,'Подготовка':10,'Проектирование':20,'В работе':45,'Разработка':45,'Ожидание':50,'На согласовании':70,'Тестирование':70,'Пилот':85,'Блокер':50,'Завершено':100,'Готово':100};

const DATA={
 goal:'Внедрить единый Business Control Center, в котором руководство и владельцы процессов видят проекты, задачи, встречи, KPI, решения, блокеры и статус исполнения в одном рабочем контуре.',
 stages:[
  ['1','Цели, границы и владелец BCC'],['2','Роли пользователей и RACI'],['3','Справочники и единая модель статусов'],['4','Портфель проектов и инициатив'],['5','Задачи, сроки и контроль исполнения'],['6','Встречи, решения и обязательства'],['7','KPI и управленческие показатели'],['8','Блокеры и эскалации'],['9','Еженедельная управленческая отчетность'],['10','Облачная синхронизация и права доступа'],['11','Пилот с рабочими командами'],['12','Приемка и переход в рабочий контур']
 ],
 teams:[
  ['Коммерческий блок','A','Приоритеты, KPI, управленческие решения'],['Корпоративные продажи','R/C','Проекты, задачи, фактическое исполнение'],['Маркетинг','R/C','Инициативы, лиды, активности и KPI'],['IT / разработка','R','Архитектура, интеграции, развитие BCC'],['DATA / BI','C/R','Показатели, источники данных, витрины'],['1С / Финансы','C','Финансовые факты и управленческие показатели'],['Информационная безопасность','C/A','Доступы, требования ИБ, допуск в рабочий контур'],['Руководители направлений','R','Актуальность задач, статусов, сроков и решений']
 ],
 modules:[
  ['Проекты','Портфель инициатив, владелец, сроки, готовность'],['Мои задачи','Исполнение, срок, приоритет, просрочка'],['Встречи','Адженда, решения, обязательства, контроль следующей встречи'],['KPI','План, факт, прогноз и отклонения'],['Блокеры','Проблемы, критичность, владелец, срок снятия'],['Решения','Вопросы, которые требуют решения руководителя'],['Команды и RACI','Ответственные и зоны ответственности'],['Отчеты','Недельная сводка: сделано, план, риски, решения'],['Справочники','Управление статусами, ролями, приоритетами и командами'],['Права доступа','Ролевой доступ и разделение видимости данных'],['Облачная синхронизация','Единое состояние между устройствами и пользователями']
 ],
 dod:[
  ['Структура BCC утверждена','Согласованы основные разделы и логика навигации'],['Роли и права доступа определены','Понятно, кто что видит и кто что изменяет'],['Проекты и задачи работают','Можно создать, назначить, изменить статус и срок'],['Встречи связаны с обязательствами','Решения и обещания не теряются после встречи'],['KPI имеют план и факт','Показатели доступны для регулярного контроля'],['Блокеры и эскалации работают','Есть владелец, критичность, срок и статус'],['Справочники редактируются','Статусы и варианты не зашиты навечно в код'],['Облачная синхронизация проверена','Изменения видны с другого устройства'],['Пилот проведен минимум на 2 командах','Собрана обратная связь реальных пользователей'],['ИБ дала допуск в рабочий контур','Нет критических замечаний по хранению и доступам'],['Еженедельный отчет формируется из BCC','Не требуется отдельный ручной реестр'],['Приемка завершена','Коммерческий директор и владельцы процессов приняли систему']
 ]
};

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
const save=(key,v)=>localStorage.setItem(key,JSON.stringify(v));
const started=()=>Boolean(localStorage.getItem(START_KEY));
const stageStatuses=()=>load(STAGES_KEY,{});
const moduleStatuses=()=>load(MODULES_KEY,{});
const teamOwners=()=>load(TEAMS_KEY,{});
const blockers=()=>load(BLOCKERS_KEY,[]);
const dodState=()=>load(DOD_KEY,{});
const activeBlockers=()=>blockers().filter(x=>!['Решен','Закрыт'].includes(x.status));
const criticalBlockers=()=>activeBlockers().filter(x=>x.severity==='Критическая').length;
const stageStatus=id=>stageStatuses()[id]||'Не начато';
const moduleStatus=i=>moduleStatuses()[i]||'Не начато';
const stageProgress=id=>started()?(PROGRESS[stageStatus(id)]||0):0;
const projectProgress=()=>started()?Math.round(DATA.stages.reduce((s,r)=>s+stageProgress(r[0]),0)/DATA.stages.length):0;
const moduleReady=()=>DATA.modules.filter((_,i)=>moduleStatus(i)==='Готово').length;
const ownerReady=()=>DATA.teams.filter((_,i)=>Boolean(teamOwners()[i])).length;
const fmtDate=ts=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'2-digit'}).format(new Date(ts));
const fmtStart=ts=>new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'medium'}).format(new Date(Number(ts)));
const addDays=(ts,d)=>Number(ts)+d*86400000;
const progress=p=>`<div class="progress"><div style="width:${Math.max(0,Math.min(100,p))}%"></div></div>`;
const options=(arr,current)=>arr.map(x=>`<option ${x===current?'selected':''}>${esc(x)}</option>`).join('');

function updateHeader(){const p=projectProgress();document.getElementById('header-progress').textContent=p+'%';document.getElementById('header-progress-bar').style.width=p+'%';}
function render(view=currentView){currentView=view;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const views={overview,gantt,roadmap,teams,modules,issues,dod,architecture};app.innerHTML=views[view]();bind();updateHeader();updateClock();}

document.querySelectorAll('.nav').forEach(btn=>btn.addEventListener('click',()=>render(btn.dataset.view)));

function overview(){const ts=localStorage.getItem(START_KEY);return `<div class="project-start-card"><div><div class="label">Статус проекта</div><div class="project-state">${started()?'Проект запущен':'Не начат'}</div><div id="project-start-at" class="start-meta">${ts?'Старт: '+fmtStart(ts):'Проект еще не начат'}</div></div><div><div class="label">Время в проекте</div><div id="project-timer" class="project-timer">00 дн. 00:00:00</div></div><button id="start-project-btn" class="btn primary" ${started()?'disabled':''}>${started()?'Проект запущен':'Старт проекта'}</button></div>
<div class="grid"><div class="card kpi"><div class="label">Готовность внедрения</div><div class="value">${projectProgress()}%</div>${progress(projectProgress())}<div class="sub">по статусам 12 этапов</div></div><div class="card kpi"><div class="label">Модули готовы</div><div class="value">${moduleReady()} / ${DATA.modules.length}</div><div class="sub">статус «Готово»</div></div><div class="card kpi"><div class="label">Владельцы назначены</div><div class="value">${ownerReady()} / ${DATA.teams.length}</div><div class="sub">команды и RACI</div></div><div class="card kpi"><div class="label">Критические блокеры</div><div class="value">${criticalBlockers()}</div><div class="sub">активные критические</div></div></div>
<div class="section-title"><h2>Цель внедрения</h2></div><div class="callout"><b>${DATA.goal}</b><br><br>Это система управления внедрением и дальнейшей операционной работой BCC, а не BI-дашборд.</div>
<div class="section-title"><h2>Контроль готовности</h2><small>Что требует внимания сейчас</small></div><div class="grid"><div class="card"><b>Этапы завершены</b><div style="font-size:28px;font-weight:700;margin-top:8px">${DATA.stages.filter(r=>stageStatus(r[0])==='Завершено').length} / ${DATA.stages.length}</div></div><div class="card"><b>Активные блокеры</b><div style="font-size:28px;font-weight:700;margin-top:8px">${activeBlockers().length}</div></div><div class="card"><b>DoD выполнено</b><div style="font-size:28px;font-weight:700;margin-top:8px">${DATA.dod.filter((_,i)=>dodState()[i]).length} / ${DATA.dod.length}</div></div><div class="card"><b>Следующий принцип</b><div style="margin-top:8px">Сначала управляем внедрением BCC, затем BCC становится рабочим центром управления бизнесом.</div></div></div>`;}

function gantt(){const ps=started()?Number(localStorage.getItem(START_KEY)):Date.now();const tasks=[['Цели и владелец',0,7],['Роли и RACI',0,14],['Справочники',7,21],['Проекты',14,28],['Задачи и сроки',21,35],['Встречи и решения',28,42],['KPI',35,49],['Блокеры и отчеты',42,56],['Права и синхронизация',49,63],['Пилот команд',56,77],['ИБ и доработки',70,84],['Приемка',84,90]];return `<div class="section-title"><h2>Диаграмма Ганта</h2><small>План внедрения на 90 дней</small></div><div class="callout"><b>${started()?'Сроки рассчитаны от фактического старта проекта.':'Проект еще не запущен. Пока показан план от сегодняшней даты.'}</b></div><div class="gantt-wrap"><div class="gantt-head"><div class="gantt-task-head">Этап</div><div class="gantt-weeks">${Array.from({length:12},(_,i)=>`<div class="gantt-week">Н${i+1}</div>`).join('')}</div></div>${tasks.map(([n,s,e])=>`<div class="gantt-row"><div class="gantt-task"><b>${n}</b><small>${fmtDate(addDays(ps,s))} - ${fmtDate(addDays(ps,e))}</small></div><div class="gantt-track"><div class="gantt-grid"></div><div class="gantt-bar" style="left:${s/90*100}%;width:${Math.max(2,(e-s)/90*100)}%"></div></div></div>`).join('')}</div><div class="gantt-footer"><span>Старт: <b>${fmtDate(ps)}</b></span><span>Плановое завершение: <b>${fmtDate(addDays(ps,90))}</b></span><span>Срок: <b>90 дней</b></span></div>`;}

function roadmap(){return `<div class="section-title"><h2>Этапы внедрения</h2><small>Статусы формируют общую готовность</small></div><table class="table"><thead><tr><th>#</th><th>Этап</th><th>Статус</th><th>Готовность</th></tr></thead><tbody>${DATA.stages.map(r=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b></td><td><select class="stage-status" data-id="${r[0]}">${options(STAGE_STATUSES,stageStatus(r[0]))}</select></td><td>${stageProgress(r[0])}% ${progress(stageProgress(r[0]))}</td></tr>`).join('')}</tbody></table>`;}

function teams(){const owners=teamOwners();return `<div class="section-title"><h2>Команды и RACI</h2><small>R делает · A отвечает · C консультирует</small></div><table class="table"><thead><tr><th>Команда</th><th>RACI</th><th>Роль</th><th>Ответственный</th></tr></thead><tbody>${DATA.teams.map((r,i)=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td><input class="team-owner" data-id="${i}" value="${esc(owners[i]||'')}" placeholder="ФИО / роль"></td></tr>`).join('')}</tbody></table>`;}

function modules(){return `<div class="section-title"><h2>Модули ATOM BCC</h2><small>Что должно войти в рабочую систему</small></div><table class="table"><thead><tr><th>Модуль</th><th>Назначение</th><th>Статус внедрения</th></tr></thead><tbody>${DATA.modules.map((r,i)=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td><select class="module-status" data-id="${i}">${options(MODULE_STATUSES,moduleStatus(i))}</select></td></tr>`).join('')}</tbody></table>`;}

function issues(){const list=blockers();return `<div class="section-title"><h2>Блокеры внедрения</h2><small>активных: ${activeBlockers().length}, критических: ${criticalBlockers()}</small></div><div class="card"><h3 style="margin-top:0">Добавить блокер</h3><div style="display:grid;grid-template-columns:1.1fr 2fr 1fr 1fr;gap:10px"><input id="bl-area" placeholder="Этап / модуль"><input id="bl-desc" placeholder="Описание проблемы"><select id="bl-sev">${options(SEVERITY,'Средняя')}</select><input id="bl-owner" placeholder="Ответственный"></div><div style="display:flex;gap:10px;margin-top:10px"><input id="bl-due" type="date"><button id="add-blocker" class="btn primary">Создать блокер</button></div></div>${list.length?`<table class="table" style="margin-top:14px"><thead><tr><th>Область</th><th>Проблема</th><th>Критичность</th><th>Ответственный</th><th>Срок</th><th>Статус</th><th></th></tr></thead><tbody>${list.map(b=>`<tr><td>${esc(b.area)}</td><td>${esc(b.desc)}</td><td><select class="bl-severity" data-id="${b.id}">${options(SEVERITY,b.severity)}</select></td><td>${esc(b.owner)}</td><td>${esc(b.due||'')}</td><td><select class="bl-status" data-id="${b.id}">${options(BLOCKER_STATUSES,b.status)}</select></td><td><button class="btn del-blocker" data-id="${b.id}">Удалить</button></td></tr>`).join('')}</tbody></table>`:'<div class="callout">Блокеров пока нет.</div>'}`;}

function dod(){const ds=dodState();return `<div class="section-title"><h2>Definition of Done</h2><small>Когда внедрение можно считать завершенным</small></div><div class="checklist">${DATA.dod.map((r,i)=>`<label class="check"><input type="checkbox" class="dod-check" data-id="${i}" ${ds[i]?'checked':''}><span><b>${r[0]}</b><small>${r[1]}</small></span></label>`).join('')}</div>`;}

function architecture(){return `<div class="section-title"><h2>Архитектура ATOM BCC</h2><small>Логика продукта</small></div><div class="callout"><b>BCC не заменяет ELMA, 1С, BI или Jira-подобные системы.</b> Он собирает управленческий слой: кто что делает, что не сделано, где блокер, какое решение нужно и что происходит с ключевыми инициативами.</div><div class="architecture"><div class="arch-row"><div class="arch-node"><b>Команды АТОМ</b><br><small>бизнес · продажи · IT · DATA · ИБ</small></div><div class="arch-arrow">→</div><div class="arch-node"><b>ATOM BCC</b><br><small>единый центр управления</small></div></div><div class="arch-row"><div class="arch-node">Проекты</div><div class="arch-node">Задачи</div><div class="arch-node">Встречи</div><div class="arch-node">Решения</div><div class="arch-node">KPI</div><div class="arch-node">Блокеры</div></div><div class="arch-row"><div class="arch-node"><b>Источники факта</b><br><small>ELMA · Альфа-Авто · 1С · DWH · BI</small></div><div class="arch-arrow">→</div><div class="arch-node"><b>Управленческий отчет</b><br><small>что сделано · риски · решения · план</small></div><div class="arch-arrow">→</div><div class="arch-node"><b>Коммерческий директор</b></div></div></div>`;}

function bind(){const start=document.getElementById('start-project-btn');if(start&&!started())start.onclick=()=>{localStorage.setItem(START_KEY,String(Date.now()));render('overview')};document.querySelectorAll('.stage-status').forEach(el=>el.onchange=()=>{const x=stageStatuses();x[el.dataset.id]=el.value;save(STAGES_KEY,x);render('roadmap')});document.querySelectorAll('.module-status').forEach(el=>el.onchange=()=>{const x=moduleStatuses();x[el.dataset.id]=el.value;save(MODULES_KEY,x);render('modules')});document.querySelectorAll('.team-owner').forEach(el=>el.onchange=()=>{const x=teamOwners();x[el.dataset.id]=el.value.trim();save(TEAMS_KEY,x);updateHeader()});document.querySelectorAll('.dod-check').forEach(el=>el.onchange=()=>{const x=dodState();x[el.dataset.id]=el.checked;save(DOD_KEY,x)});const add=document.getElementById('add-blocker');if(add)add.onclick=()=>{const area=document.getElementById('bl-area').value.trim(),desc=document.getElementById('bl-desc').value.trim();if(!area||!desc)return alert('Укажите область и описание блокера');const x=blockers();x.push({id:Date.now().toString(36),area,desc,severity:document.getElementById('bl-sev').value,owner:document.getElementById('bl-owner').value.trim(),due:document.getElementById('bl-due').value,status:'Открыт'});save(BLOCKERS_KEY,x);render('issues')};document.querySelectorAll('.bl-status').forEach(el=>el.onchange=()=>updateBlocker(el.dataset.id,'status',el.value));document.querySelectorAll('.bl-severity').forEach(el=>el.onchange=()=>updateBlocker(el.dataset.id,'severity',el.value));document.querySelectorAll('.del-blocker').forEach(el=>el.onclick=()=>{save(BLOCKERS_KEY,blockers().filter(x=>x.id!==el.dataset.id));render('issues')});}
function updateBlocker(id,key,val){const x=blockers();const b=x.find(i=>i.id===id);if(b)b[key]=val;save(BLOCKERS_KEY,x);render('issues')}
function updateClock(){clearInterval(timerHandle);const tick=()=>{const el=document.getElementById('project-timer'),ts=localStorage.getItem(START_KEY);if(!el)return;if(!ts){el.textContent='00 дн. 00:00:00';return}const s=Math.max(0,Math.floor((Date.now()-Number(ts))/1000)),d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),ss=s%60,p=n=>String(n).padStart(2,'0');el.textContent=`${d} дн. ${p(h)}:${p(m)}:${p(ss)}`};tick();timerHandle=setInterval(tick,1000)}
window.addEventListener('atom-sync-ready',()=>render(currentView));window.addEventListener('atom-sync-update',()=>render(currentView));
render('overview');